### ISSUE TITLE
Unicode username support?

### ISSUE THREAD

**Issue by jarek** [osm-hr/my-osm-notes#1]
Hello,

Thanks for making this util! I've been looking for exactly this, but it seems to stumble over a Unicode character in my OSM username.

My username is https://www.openstreetmap.org/user/Jarek%20Pi%C3%B3rkowski and my OSM uid is 1768286. http://my-notes.osm-hr.org/myosmnotes.cgi?ignoreold=&s=Jarek%20Pi%C3%B3rkowski doesn't show any of my open notes.

The error message it gives suggests that encoding could be the issue: "Searching for OSM Notes for users: Jarek PiÃ³rkowski(0) No open notes found." What should be ó (U+00F3, URL-encoded as %C3%B3) is reproduced as "Ã³" (U+00C3 U+00B3).

Unfortunately I know next to nothing about Unicode support or databases in Perl, so I can't try to help myself. Is this something that would be a relatively simple fix for you? Alternatively, would it be possible to search by uid in addition to username?

Thanks again,
--Jarek

**Comment by hbogner** [comment]
@mnalis can you fix this?

**Comment by mnalis** [comment]
Thanks @jarek  for your bug report!

The UTF8 issue in my-osm-notes should be solved now and available online. Sorry it took some time...
(fully fixed in git commit d472f8f02b26787e1b52ad0ecc98753ad388f5b9)

**Comment by jarek** [comment]
Super, can confirm this works now! Thanks again for hosting this service :D
